# Generated by Django 5.1.1 on 2024-11-23 13:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_card_user_remove_wallet_user_card_customer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentwithdate',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paymentwithdate',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='paymentbywallet',
            name='wallet',
        ),
        migrations.RenameField(
            model_name='paymentbycard',
            old_name='card',
            new_name='saved_card',
        ),
        migrations.RemoveField(
            model_name='paymentbywallet',
            name='amount_in_wallet',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='paymentbycard',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paymentbycard',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentbycard',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(default=None, limit_choices_to={'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentDate',
        ),
        migrations.DeleteModel(
            name='PaymentWithDate',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
