# Generated by Django 5.1.1 on 2024-11-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='M_TotalItems',
            field=models.IntegerField(default=0),
        ),
    ]
