# Generated by Django 5.1.1 on 2024-11-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='type',
            field=models.CharField(default='door', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.CharField(default='table', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='window',
            name='type',
            field=models.CharField(default='window', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='layout',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layout',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
