# Generated by Django 5.1.1 on 2024-11-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restuarant',
            new_name='Restaurant',
        ),
    ]
