# Generated by Django 5.1.1 on 2024-11-16 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_restuarant_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='restaurant.layout'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurant.restaurant'),
        ),
    ]
