# Generated by Django 5.1.1 on 2024-11-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_door_type_table_type_window_type_alter_layout_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='door',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='window',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='window',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
