# Generated by Django 5.1.1 on 2024-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_door_x_position_alter_door_y_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='x_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='y_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='x_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='y_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='x_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='y_position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
